version: "3"

services:
  
  prueba_django:
    image: python:3.9.5
    container_name: prueba_djangoISDM
    restart: always
    volumes:
      - type: bind
        source: .
        target: /opt/back_end
    ports:
      - "8000:8000"
    stdin_open: true
    tty: true
  
  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: db
      MYSQL_USER: nico
      MYSQL_PASSWORD: 12345
      MYSQL_ROOT_PASSWORD: root

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - "9090:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - "8081:8080"
    depends_on:
      - mysql

volumes:
  mysql-data:

    
